version: '3.8'

services:
    api:
        build:
            context: ./api
        container_name: api-algoquest
        env_file:
            - .env
        ports:
            - "${API_PORT}:8080"
        depends_on:
            mongo:
                condition: service_healthy
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 20s
        networks:
            - algoquest-net

    mongo:
        image: mongo:6
        container_name: mongo-algoquest
        restart: always
        env_file:
            - .env
        volumes:
            - ./mongo-init:/docker-entrypoint-initdb.d
            - mongo_data:/data/db
        healthcheck:
            test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 20s
        networks:
            - algoquest-net

volumes:
    mongo_data:


networks:
    algoquest-net:
