version: '3.8'

services:
    api:
        build:
            context: ./api
        container_name: api-algoquest
        env_file:
            - .env
        ports:
            - "${API_PORT}:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - algoquest_tmp:/tmp/algoquest
        depends_on:
            mongo:
                condition: service_healthy
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 20s
        networks:
            - algoquest-net

    sandbox-java:
        build:
            context: .
            dockerfile: ./api/Dockerfile.sandbox
        image: algoquest-sandbox
        volumes:
            - algoquest_tmp:/tmp/algoquest

    mongo:
        image: mongo:6
        container_name: mongo-algoquest
        restart: always
        env_file:
            - .env
        volumes:
            - ./mongo-init:/docker-entrypoint-initdb.d
            - mongo_data:/data/db
        healthcheck:
            test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 20s
        networks:
            - algoquest-net

    mongo-express:
        image: mongo-express:1.0.2
        container_name: mongo-express-algoquest
        restart: always
        ports:
            - "${MONGO_EXPRESS_PORT}:8081"
        env_file:
            - .env
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
            ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
        depends_on:
            mongo:
                condition: service_healthy
        healthcheck:
            test: ["CMD", "curl", "-fsu", "${MONGO_EXPRESS_USER}:${MONGO_EXPRESS_PASSWORD}", "http://localhost:8081/"]
            interval: 30s
            timeout: 10s
            retries: 10
            start_period: 60s
        networks:
            - algoquest-net

volumes:
    mongo_data:
    algoquest_tmp:


networks:
    algoquest-net:
