version: '3.8'

services:
  api:
    build:
      context: ./api
    container_name: api-algoquest
    env_file:
      - .env
    ports:
      - "${API_PORT}:8080"
    depends_on:
      - mongo
    networks:
      - algoquest-net

  mongo:
    image: mongo:6
    container_name: mongo-algoquest
    restart: always
    env_file:
      - .env
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d
      - mongo_data:/data/db
    networks:
      - algoquest-net

volumes:
  mongo_data:

networks:
  algoquest-net:
