version: '3.8'

services:
  api:
    build:
      context: ./api
    ports:
      - "${API_PORT}:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://algoquest_user:securepassword@mongo:27017/algoquest?authSource=algoquest
    depends_on:
      - mongo
    networks:
      - algoquest-net

  mongo:
    image: mongo:6
    container_name: mongo-algoquest
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - algoquest-net

volumes:
  mongo_data:

networks:
  algoquest-net:
